"""
Django settings for EmberLight project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Load Gemini Api Key for chat app
#GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "supersecret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#ALLOWED_HOSTS = ['emberlight.mehdi.cat','emberlight.mehdi.cat', '54.209.17.170']

ALLOWED_HOSTS = [
    'emberlight.mehdi.cat',
    'emberlight.mehdi.cat', 
    '54.209.17.170',
    '127.0.0.1',
    'localhost'
]
# Static files (CSS, JavaScript, Images)
#STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, '../../staticfiles')  # Where collectstatic will put files

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# For React's built static files
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, '../../../frontend/build/static'),  # Path to React's built static files
#]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', '..', 'frontend', 'build', 'static'),
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'login',
    'chat',
    'journal',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True # To prevent errors like "blocked by CORS policy"
#CORS_ALLOWED_ORIGINS = [
    #"https://yourdomain.com",  # For React EC2 or Amplify deployment. Not in use yet.
    #"http://localhost:3000",
#    "https://emberlight.mehdi.cat"    # For development
#]
CORS_ALLOWED_ORIGINS = [
    "https://emberlight.mehdi.cat",
    "https://emberlight.mehdi.cat"
]
CORS_EXPOSE_HEADERS = ['X-CSRFToken']

# Security, for production
SESSION_COOKIE_SECURE = True    # HTTPS only
CSRF_COOKIE_SECURE = True       # HTTPS only
#CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
#CSRF_TRUSTED_ORIGINS = [
#    "https://emberlight.mehdi.cat",
#    "https://emberlight.mehdi.cat"
#]

CSRF_TRUSTED_ORIGINS = [
    "https://emberlight.mehdi.cat",
    "https://emberlight.mehdi.cat"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Session authentication
SESSION_COOKIE_SAMESITE = 'Lax'  # To prevent CSRF attacks
SESSION_COOKIE_HTTPONLY = True   # To prevent XSS

ROOT_URLCONF = 'EmberLight.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EmberLight.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "login.User"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
